[workspace]
members = [
    "crates/cli",
    "crates/recon",
]

[workspace.package]
version = "0.2.0"
authors = ["Ervin Szilagyi"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/domain-recon/domain-recon-rs"
repository = "https://github.com/domain-recon/domain-recon-rs"
keywords = ["domain", "recon"]
description = "Cargo subcommand to work with AWS Lambda"
rust-version = "1.64.0"

[workspace.dependencies]
recon = {version = "0.2.0", path = "crates/recon"}

[profile.release]
strip = "symbols"
