[package]
name = "domain-recon-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0.2", features = ["full"] }
exitfailure = "0.5.1"
futures = "0.3.24"
async-std-resolver = "0.22.0"
clap = { version = "4.0.18", features = ["derive"] }
csv = "1.1.6"
