[workspace]
members = [
    "crates/cli",
    "crates/recon",
]

[workspace.package]
version = "0.7.1"
authors = ["Ervin Szilagyi"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/domain-recon/domain-recon-rs"
repository = "https://github.com/domain-recon/domain-recon-rs"
keywords = ["domain", "recon"]
description = "Extract domains and subdomains from certificates."
rust-version = "1.64.0"

[workspace.dependencies]
recon = { version = "0.7.1", path = "crates/recon" }
tokio = { version = "1.0.2" }
anyhow = { version = "1.0.66" }
console = { version = "0.15.2" }

[profile.release]
strip = "symbols"
